#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.5.0
# from Racc grammar file "".
#

require 'racc/parser.rb'

  require "./lexer.rb"
  require "./nodes.rb"

class Parser < Racc::Parser

module_eval(<<'...end grammar.y.rb/module_eval...', 'grammar.y.rb', 135)
  def parse(code, show_tokens=false)
    @tokens = Lexer.new.tokenize(code)
    puts @tokens.inspect if show_tokens
    do_parse
  end
  
  def next_token
    @tokens.shift
  end
  
...end grammar.y.rb/module_eval...
##### State transition tables begin ###

racc_action_table = [
    23,     5,    16,    17,    18,    19,    20,    21,    22,    23,
     5,    16,    17,    18,    19,    20,    21,    22,    26,    26,
    27,    27,    38,    39,    36,    37,    14,    78,    15,    27,
    45,    38,    39,    36,    37,    14,    23,    15,    16,    17,
    18,    19,    20,    21,    22,    15,    15,    23,    46,    16,
    17,    18,    19,    20,    21,    22,    27,    49,    38,    39,
    36,    37,    14,    64,    23,    75,    16,    17,    18,    19,
    20,    21,    22,    14,    23,    47,    16,    17,    18,    19,
    20,    21,    22,    27,    24,    38,    39,    36,    37,    23,
    14,    16,    17,    18,    19,    20,    21,    22,    27,    23,
    14,    16,    17,    18,    19,    20,    21,    22,    27,    70,
    38,    39,    68,    43,    23,    14,    16,    17,    18,    19,
    20,    21,    22,    81,    23,    14,    16,    17,    18,    19,
    20,    21,    22,    27,    68,    38,    39,   nil,   nil,    23,
    14,    16,    17,    18,    19,    20,    21,    22,   nil,    23,
    14,    16,    17,    18,    19,    20,    21,    22,    73,    44,
    72,    43,   nil,   nil,    23,    14,    16,    17,    18,    19,
    20,    21,    22,   nil,    23,    14,    16,    17,    18,    19,
    20,    21,    22,    79,   nil,    80,   nil,   nil,   nil,    23,
    14,    16,    17,    18,    19,    20,    21,    22,   nil,    23,
    14,    16,    17,    18,    19,    20,    21,    22,   nil,   nil,
   nil,   nil,   nil,   nil,    23,    14,    16,    17,    18,    19,
    20,    21,    22,   nil,    23,    14,    16,    17,    18,    19,
    20,    21,    22,   nil,   nil,   nil,   nil,   nil,   nil,    23,
    14,    16,    17,    18,    19,    20,    21,    22,   nil,    23,
    14,    16,    17,    18,    19,    20,    21,    22,   nil,   nil,
   nil,   nil,   nil,   nil,    23,    14,    16,    17,    18,    19,
    20,    21,    22,   nil,    27,    14,    38,    39,    36,    37,
    32,    33,    34,    35,    30,    31,    29,    28,   nil,   nil,
    14,    62,    27,   nil,    38,    39,    36,    37,    32,    33,
    34,    35,    30,    31,    29,    28,    27,   nil,    38,    39,
    36,    37,    32,    33,    34,    35,    30,    31,    29,    28,
    27,   nil,    38,    39,    36,    37,    32,    33,    34,    35,
    30,    31,    29,    28,    27,   nil,    38,    39,    36,    37,
    32,    33,    34,    35,    30,    31,    29,    28,    27,   nil,
    38,    39,    36,    37,    32,    33,    34,    35,    30,    31,
    29,    28,    27,   nil,    38,    39,    36,    37,    32,    33,
    34,    35,    30,    31,    29,    28,    27,   nil,    38,    39,
    36,    37,    32,    33,    34,    35,    30,    31,    29,    28,
    27,   nil,    38,    39,    36,    37,    32,    33,    34,    35,
    30,    31,    29,    27,   nil,    38,    39,    36,    37,    32,
    33,    34,    35,    30,    31,    27,   nil,    38,    39,    36,
    37,    32,    33,    34,    35,    27,   nil,    38,    39,    36,
    37,    32,    33,    34,    35 ]

racc_action_check = [
    68,    68,    68,    68,    68,    68,    68,    68,    68,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     2,    74,
    56,    60,    56,    56,    56,    56,    68,    74,    68,    54,
    22,    54,    54,    54,    54,     0,    43,     0,    43,    43,
    43,    43,    43,    43,    43,     2,    74,    73,    23,    73,
    73,    73,    73,    73,    73,    73,    55,    27,    55,    55,
    55,    55,    43,    43,    45,    70,    45,    45,    45,    45,
    45,    45,    45,    73,    44,    24,    44,    44,    44,    44,
    44,    44,    44,    57,     1,    57,    57,    57,    57,    14,
    45,    14,    14,    14,    14,    14,    14,    14,    61,     5,
    44,     5,     5,     5,     5,     5,     5,     5,    58,    46,
    58,    58,    46,    49,    25,    14,    25,    25,    25,    25,
    25,    25,    25,    79,    39,     5,    39,    39,    39,    39,
    39,    39,    39,    59,    80,    59,    59,   nil,   nil,    28,
    25,    28,    28,    28,    28,    28,    28,    28,   nil,    29,
    39,    29,    29,    29,    29,    29,    29,    29,    65,    21,
    65,    21,   nil,   nil,    30,    28,    30,    30,    30,    30,
    30,    30,    30,   nil,    31,    29,    31,    31,    31,    31,
    31,    31,    31,    76,   nil,    76,   nil,   nil,   nil,    32,
    30,    32,    32,    32,    32,    32,    32,    32,   nil,    33,
    31,    33,    33,    33,    33,    33,    33,    33,   nil,   nil,
   nil,   nil,   nil,   nil,    34,    32,    34,    34,    34,    34,
    34,    34,    34,   nil,    35,    33,    35,    35,    35,    35,
    35,    35,    35,   nil,   nil,   nil,   nil,   nil,   nil,    36,
    34,    36,    36,    36,    36,    36,    36,    36,   nil,    37,
    35,    37,    37,    37,    37,    37,    37,    37,   nil,   nil,
   nil,   nil,   nil,   nil,    38,    36,    38,    38,    38,    38,
    38,    38,    38,   nil,    41,    37,    41,    41,    41,    41,
    41,    41,    41,    41,    41,    41,    41,    41,   nil,   nil,
    38,    41,    40,   nil,    40,    40,    40,    40,    40,    40,
    40,    40,    40,    40,    40,    40,    77,   nil,    77,    77,
    77,    77,    77,    77,    77,    77,    77,    77,    77,    77,
     3,   nil,     3,     3,     3,     3,     3,     3,     3,     3,
     3,     3,     3,     3,    67,   nil,    67,    67,    67,    67,
    67,    67,    67,    67,    67,    67,    67,    67,    66,   nil,
    66,    66,    66,    66,    66,    66,    66,    66,    66,    66,
    66,    66,    63,   nil,    63,    63,    63,    63,    63,    63,
    63,    63,    63,    63,    63,    63,    48,   nil,    48,    48,
    48,    48,    48,    48,    48,    48,    48,    48,    48,    48,
    50,   nil,    50,    50,    50,    50,    50,    50,    50,    50,
    50,    50,    50,    51,   nil,    51,    51,    51,    51,    51,
    51,    51,    51,    51,    51,    52,   nil,    52,    52,    52,
    52,    52,    52,    52,    52,    53,   nil,    53,    53,    53,
    53,    53,    53,    53,    53 ]

racc_action_pointer = [
     7,    84,    15,   308,   nil,    97,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    87,   nil,   nil,   nil,   nil,   nil,
   nil,   133,     4,    39,    75,   112,   nil,    48,   137,   147,
   162,   172,   187,   197,   212,   222,   237,   247,   262,   122,
   280,   262,   nil,    34,    72,    62,    81,   nil,   364,    85,
   378,   391,   403,   413,    17,    44,     8,    71,    96,   121,
     9,    86,   nil,   350,   nil,   131,   336,   322,    -2,   nil,
    56,   nil,   nil,    45,    16,   nil,   156,   294,   nil,   114,
   103,   nil,   nil ]

racc_action_default = [
    -1,   -53,    -2,    -3,    -6,   -17,    -8,    -9,   -10,   -11,
   -12,   -13,   -14,   -15,   -53,   -18,   -19,   -20,   -21,   -22,
   -23,   -48,   -46,   -53,   -53,    -5,   -17,   -53,   -53,   -53,
   -53,   -53,   -53,   -53,   -53,   -53,   -53,   -53,   -53,   -53,
    -7,   -53,   -24,   -53,   -53,   -53,   -53,    83,    -4,   -26,
   -34,   -35,   -36,   -37,   -38,   -39,   -40,   -41,   -42,   -43,
   -44,   -45,   -16,   -29,   -27,   -53,   -49,   -47,   -53,   -51,
   -31,   -25,   -28,   -53,   -53,   -32,   -53,   -30,   -50,   -53,
   -53,   -33,   -52 ]

racc_goto_table = [
    25,    40,     2,    69,    76,    65,     1,   nil,    42,   nil,
    41,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    48,   nil,   nil,    50,    51,    52,    53,    54,    55,
    56,    57,    58,    59,    60,    61,    71,    82,   nil,    63,
    66,    67,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    77,
    74,   nil,    25 ]

racc_goto_check = [
     4,     3,     2,    16,    15,    14,     1,   nil,    13,   nil,
     3,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,     3,   nil,   nil,     3,     3,     3,     3,     3,     3,
     3,     3,     3,     3,     3,     3,    13,    16,   nil,     3,
     3,     3,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     3,
     2,   nil,     4 ]

racc_goto_pointer = [
   nil,     6,     2,    -4,    -2,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   -13,   -38,   -66,   -43 ]

racc_goto_default = [
   nil,   nil,   nil,     3,     4,     6,     7,     8,     9,    10,
    11,    12,    13,   nil,   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  0, 33, :_reduce_1,
  1, 33, :_reduce_2,
  1, 34, :_reduce_3,
  3, 34, :_reduce_4,
  2, 34, :_reduce_5,
  1, 34, :_reduce_6,
  2, 34, :_reduce_7,
  1, 35, :_reduce_none,
  1, 35, :_reduce_none,
  1, 35, :_reduce_none,
  1, 35, :_reduce_none,
  1, 35, :_reduce_none,
  1, 35, :_reduce_none,
  1, 35, :_reduce_none,
  1, 35, :_reduce_none,
  3, 35, :_reduce_16,
  1, 36, :_reduce_none,
  1, 36, :_reduce_none,
  1, 37, :_reduce_19,
  1, 37, :_reduce_20,
  1, 37, :_reduce_21,
  1, 37, :_reduce_22,
  1, 37, :_reduce_23,
  2, 38, :_reduce_24,
  4, 38, :_reduce_25,
  3, 38, :_reduce_26,
  2, 45, :_reduce_27,
  3, 45, :_reduce_28,
  1, 46, :_reduce_29,
  3, 46, :_reduce_30,
  0, 47, :_reduce_31,
  1, 47, :_reduce_32,
  3, 47, :_reduce_33,
  3, 39, :_reduce_34,
  3, 39, :_reduce_35,
  3, 39, :_reduce_36,
  3, 39, :_reduce_37,
  3, 39, :_reduce_38,
  3, 39, :_reduce_39,
  3, 39, :_reduce_40,
  3, 39, :_reduce_41,
  3, 39, :_reduce_42,
  3, 39, :_reduce_43,
  3, 39, :_reduce_44,
  3, 39, :_reduce_45,
  1, 40, :_reduce_46,
  3, 41, :_reduce_47,
  1, 42, :_reduce_48,
  3, 43, :_reduce_49,
  3, 48, :_reduce_50,
  3, 44, :_reduce_51,
  6, 44, :_reduce_52 ]

racc_reduce_n = 53

racc_shift_n = 83

racc_token_table = {
  false => 0,
  :error => 1,
  :DEF => 2,
  :NEWLINE => 3,
  :NUMBER => 4,
  :STRING => 5,
  :TRUE => 6,
  :FALSE => 7,
  :NIL => 8,
  :IDENTIFIER => 9,
  :CONSTANT => 10,
  :END => 11,
  "." => 12,
  "!" => 13,
  "*" => 14,
  "/" => 15,
  "+" => 16,
  "-" => 17,
  ">" => 18,
  ">=" => 19,
  "<" => 20,
  "<=" => 21,
  "==" => 22,
  "!=" => 23,
  "&&" => 24,
  "||" => 25,
  "=" => 26,
  "," => 27,
  "(" => 28,
  ")" => 29,
  ";" => 30,
  ":" => 31 }

racc_nt_base = 32

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "DEF",
  "NEWLINE",
  "NUMBER",
  "STRING",
  "TRUE",
  "FALSE",
  "NIL",
  "IDENTIFIER",
  "CONSTANT",
  "END",
  "\".\"",
  "\"!\"",
  "\"*\"",
  "\"/\"",
  "\"+\"",
  "\"-\"",
  "\">\"",
  "\">=\"",
  "\"<\"",
  "\"<=\"",
  "\"==\"",
  "\"!=\"",
  "\"&&\"",
  "\"||\"",
  "\"=\"",
  "\",\"",
  "\"(\"",
  "\")\"",
  "\";\"",
  "\":\"",
  "$start",
  "Program",
  "Expressions",
  "Expression",
  "Terminator",
  "Literal",
  "Call",
  "Operator",
  "GetConstant",
  "SetConstant",
  "GetLocal",
  "SetLocal",
  "Def",
  "Arguments",
  "ArgList",
  "ParamList",
  "Block" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'grammar.y.rb', 28)
  def _reduce_1(val, _values, result)
     result = Nodes.new([])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 29)
  def _reduce_2(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 33)
  def _reduce_3(val, _values, result)
     result = Nodes.new(val)
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 34)
  def _reduce_4(val, _values, result)
     result = val[0] << val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 35)
  def _reduce_5(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 36)
  def _reduce_6(val, _values, result)
     result = Nodes.new([])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 37)
  def _reduce_7(val, _values, result)
     result = val[1]
    result
  end
.,.,

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

# reduce 15 omitted

module_eval(<<'.,.,', 'grammar.y.rb', 49)
  def _reduce_16(val, _values, result)
     result = val[1]
    result
  end
.,.,

# reduce 17 omitted

# reduce 18 omitted

module_eval(<<'.,.,', 'grammar.y.rb', 58)
  def _reduce_19(val, _values, result)
     result = NumberNode.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 59)
  def _reduce_20(val, _values, result)
     result = StringNode.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 60)
  def _reduce_21(val, _values, result)
     result = TrueNode.new
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 61)
  def _reduce_22(val, _values, result)
     result = FalseNode.new
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 62)
  def _reduce_23(val, _values, result)
     result = NilNode.new
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 66)
  def _reduce_24(val, _values, result)
     result = CallNode.new(nil, val[0], val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 68)
  def _reduce_25(val, _values, result)
     result = CallNode.new(val[0], val[2], val[3])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 69)
  def _reduce_26(val, _values, result)
     result = CallNode.new(val[0], val[2], [])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 73)
  def _reduce_27(val, _values, result)
     result = []
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 74)
  def _reduce_28(val, _values, result)
     result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 78)
  def _reduce_29(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 79)
  def _reduce_30(val, _values, result)
     result = val[0] << val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 83)
  def _reduce_31(val, _values, result)
     result = []
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 84)
  def _reduce_32(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 85)
  def _reduce_33(val, _values, result)
     result = val[0] << val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 89)
  def _reduce_34(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 90)
  def _reduce_35(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 91)
  def _reduce_36(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 92)
  def _reduce_37(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 93)
  def _reduce_38(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 94)
  def _reduce_39(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 95)
  def _reduce_40(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 96)
  def _reduce_41(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 97)
  def _reduce_42(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 98)
  def _reduce_43(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 99)
  def _reduce_44(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 100)
  def _reduce_45(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 104)
  def _reduce_46(val, _values, result)
     result = GetConstantNode.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 108)
  def _reduce_47(val, _values, result)
     result = SetConstantNode.new(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 112)
  def _reduce_48(val, _values, result)
     result = GetLocalNode.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 116)
  def _reduce_49(val, _values, result)
     result = SetLocalNode.new(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 120)
  def _reduce_50(val, _values, result)
     result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 124)
  def _reduce_51(val, _values, result)
     result = DefNode.new(val[1], [], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 126)
  def _reduce_52(val, _values, result)
     result = DefNode.new(val[1], val[3], val[5])
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class Parser
