#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.5.0
# from Racc grammar file "".
#

require 'racc/parser.rb'

  require "#{File.dirname(__FILE__)}/lexer.rb"
  require "#{File.dirname(__FILE__)}/nodes.rb"

class Parser < Racc::Parser

module_eval(<<'...end grammar.y.rb/module_eval...', 'grammar.y.rb', 153)
  def parse(code, show_tokens=false)
    @tokens = Lexer.new.tokenize(code)
    puts @tokens.inspect if show_tokens
    do_parse
  end
  
  def next_token
    @tokens.shift
  end
  
...end grammar.y.rb/module_eval...
##### State transition tables begin ###

racc_action_table = [
    27,    28,     5,    19,    20,    21,    22,    23,    24,    25,
    31,    31,    27,    28,    76,    19,    20,    21,    22,    23,
    24,    25,    84,    32,    83,    49,    55,    17,    31,    18,
    26,    89,    32,    88,    43,    44,    92,    18,    18,    17,
    48,    93,    26,    27,    28,    54,    19,    20,    21,    22,
    23,    24,    25,    27,    28,    18,    19,    20,    21,    22,
    23,    24,    25,    49,    32,    53,    43,    44,    41,    42,
    17,    52,    32,    26,    43,    44,    50,    94,    48,    95,
    17,    27,    28,    26,    19,    20,    21,    22,    23,    24,
    25,    27,    28,    51,    19,    20,    21,    22,    23,    24,
    25,    32,    57,    43,    44,    41,    42,    29,    17,    72,
    80,    26,    77,    78,    77,    78,    77,    78,    17,    27,
    28,    26,    19,    20,    21,    22,    23,    24,    25,    27,
    28,    96,    19,    20,    21,    22,    23,    24,    25,    32,
    32,    43,    44,    41,    42,   nil,    17,   nil,    32,    26,
    43,    44,    41,    42,   nil,   nil,    17,    27,    28,    26,
    19,    20,    21,    22,    23,    24,    25,    27,    28,   nil,
    19,    20,    21,    22,    23,    24,    25,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    17,   nil,   nil,    26,   nil,   nil,
   nil,   nil,   nil,   nil,    17,   nil,   nil,    26,    27,    28,
     5,    19,    20,    21,    22,    23,    24,    25,    27,    28,
   nil,    19,    20,    21,    22,    23,    24,    25,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    17,   nil,    18,    26,   nil,
   nil,   nil,   nil,   nil,   nil,    17,   nil,   nil,    26,    27,
    28,     5,    19,    20,    21,    22,    23,    24,    25,    27,
    28,   nil,    19,    20,    21,    22,    23,    24,    25,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    17,   nil,    18,    26,
   nil,   nil,   nil,   nil,   nil,   nil,    17,    27,    28,    26,
    19,    20,    21,    22,    23,    24,    25,    27,    28,   nil,
    19,    20,    21,    22,    23,    24,    25,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    17,   nil,   nil,    26,   nil,   nil,
   nil,   nil,   nil,   nil,    17,    27,    28,    26,    19,    20,
    21,    22,    23,    24,    25,    27,    28,   nil,    19,    20,
    21,    22,    23,    24,    25,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    17,   nil,   nil,    26,   nil,   nil,   nil,   nil,
   nil,   nil,    17,    27,    28,    26,    19,    20,    21,    22,
    23,    24,    25,    27,    28,   nil,    19,    20,    21,    22,
    23,    24,    25,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    17,   nil,   nil,    26,   nil,   nil,   nil,   nil,   nil,   nil,
    17,    27,    28,    26,    19,    20,    21,    22,    23,    24,
    25,    27,    28,   nil,    19,    20,    21,    22,    23,    24,
    25,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    17,   nil,
   nil,    26,   nil,   nil,   nil,   nil,   nil,   nil,    17,    27,
    28,    26,    19,    20,    21,    22,    23,    24,    25,   nil,
    32,   nil,    43,    44,    41,    42,    37,    38,    39,    40,
    35,    36,    34,    33,   nil,   nil,    17,    70,    32,    26,
    43,    44,    41,    42,    37,    38,    39,    40,    35,    36,
    34,    33,    32,   nil,    43,    44,    41,    42,    37,    38,
    39,    40,    35,    36,    34,    33,    32,   nil,    43,    44,
    41,    42,    37,    38,    39,    40,    35,    36,    34,    33,
    32,   nil,    43,    44,    41,    42,    37,    38,    39,    40,
    35,    36,    34,    33,    32,   nil,    43,    44,    41,    42,
    37,    38,    39,    40,    35,    36,    34,    33,    32,   nil,
    43,    44,    41,    42,    37,    38,    39,    40,    35,    36,
    34,    33,    32,   nil,    43,    44,    41,    42,    37,    38,
    39,    40,    35,    36,    34,    33,    32,   nil,    43,    44,
    41,    42,    37,    38,    39,    40,    35,    36,    34,    33,
    32,   nil,    43,    44,    41,    42,    37,    38,    39,    40,
    35,    36,    34,    32,   nil,    43,    44,    41,    42,    37,
    38,    39,    40,    35,    36,    32,   nil,    43,    44,    41,
    42,    37,    38,    39,    40,    32,   nil,    43,    44,    41,
    42,    37,    38,    39,    40 ]

racc_action_check = [
    78,    78,    78,    78,    78,    78,    78,    78,    78,    78,
    87,     2,    50,    50,    52,    50,    50,    50,    50,    50,
    50,    50,    73,    69,    73,    57,    29,    78,    86,    78,
    78,    80,    66,    78,    66,    66,    86,    87,     2,    50,
    57,    87,    50,     5,     5,    28,     5,     5,     5,     5,
     5,     5,     5,    17,    17,    86,    17,    17,    17,    17,
    17,    17,    17,    24,    64,    27,    64,    64,    64,    64,
     5,    26,    67,     5,    67,    67,    24,    90,    24,    90,
    17,    48,    48,    17,    48,    48,    48,    48,    48,    48,
    48,    51,    51,    25,    51,    51,    51,    51,    51,    51,
    51,    65,    32,    65,    65,    65,    65,     1,    48,    48,
    53,    48,    95,    95,    53,    53,    54,    54,    51,    76,
    76,    51,    76,    76,    76,    76,    76,    76,    76,    44,
    44,    94,    44,    44,    44,    44,    44,    44,    44,    63,
    68,    63,    63,    63,    63,   nil,    76,   nil,    62,    76,
    62,    62,    62,    62,   nil,   nil,    44,    43,    43,    44,
    43,    43,    43,    43,    43,    43,    43,    84,    84,   nil,
    84,    84,    84,    84,    84,    84,    84,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    43,   nil,   nil,    43,   nil,   nil,
   nil,   nil,   nil,   nil,    84,   nil,   nil,    84,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,    30,    30,
   nil,    30,    30,    30,    30,    30,    30,    30,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,     0,   nil,     0,     0,   nil,
   nil,   nil,   nil,   nil,   nil,    30,   nil,   nil,    30,    77,
    77,    77,    77,    77,    77,    77,    77,    77,    77,    33,
    33,   nil,    33,    33,    33,    33,    33,    33,    33,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    77,   nil,    77,    77,
   nil,   nil,   nil,   nil,   nil,   nil,    33,    34,    34,    33,
    34,    34,    34,    34,    34,    34,    34,    35,    35,   nil,
    35,    35,    35,    35,    35,    35,    35,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    34,   nil,   nil,    34,   nil,   nil,
   nil,   nil,   nil,   nil,    35,    36,    36,    35,    36,    36,
    36,    36,    36,    36,    36,    37,    37,   nil,    37,    37,
    37,    37,    37,    37,    37,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    36,   nil,   nil,    36,   nil,   nil,   nil,   nil,
   nil,   nil,    37,    38,    38,    37,    38,    38,    38,    38,
    38,    38,    38,    39,    39,   nil,    39,    39,    39,    39,
    39,    39,    39,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    38,   nil,   nil,    38,   nil,   nil,   nil,   nil,   nil,   nil,
    39,    40,    40,    39,    40,    40,    40,    40,    40,    40,
    40,    41,    41,   nil,    41,    41,    41,    41,    41,    41,
    41,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    40,   nil,
   nil,    40,   nil,   nil,   nil,   nil,   nil,   nil,    41,    42,
    42,    41,    42,    42,    42,    42,    42,    42,    42,   nil,
    46,   nil,    46,    46,    46,    46,    46,    46,    46,    46,
    46,    46,    46,    46,   nil,   nil,    42,    46,     3,    42,
     3,     3,     3,     3,     3,     3,     3,     3,     3,     3,
     3,     3,    45,   nil,    45,    45,    45,    45,    45,    45,
    45,    45,    45,    45,    45,    45,    91,   nil,    91,    91,
    91,    91,    91,    91,    91,    91,    91,    91,    91,    91,
    74,   nil,    74,    74,    74,    74,    74,    74,    74,    74,
    74,    74,    74,    74,    75,   nil,    75,    75,    75,    75,
    75,    75,    75,    75,    75,    75,    75,    75,    56,   nil,
    56,    56,    56,    56,    56,    56,    56,    56,    56,    56,
    56,    56,    85,   nil,    85,    85,    85,    85,    85,    85,
    85,    85,    85,    85,    85,    85,    71,   nil,    71,    71,
    71,    71,    71,    71,    71,    71,    71,    71,    71,    71,
    58,   nil,    58,    58,    58,    58,    58,    58,    58,    58,
    58,    58,    58,    59,   nil,    59,    59,    59,    59,    59,
    59,    59,    59,    59,    59,    61,   nil,    61,    61,    61,
    61,    61,    61,    61,    61,    60,   nil,    60,    60,    60,
    60,    60,    60,    60,    60 ]

racc_action_pointer = [
   196,   107,     7,   445,   nil,    41,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    51,   nil,   nil,
   nil,   nil,   nil,   nil,    49,    66,    61,    55,    34,    26,
   206,   nil,    92,   247,   275,   285,   313,   323,   351,   361,
   389,   399,   427,   155,   127,   459,   427,   nil,    79,   nil,
    10,    89,   -13,    81,    83,   nil,   515,    11,   557,   570,
   592,   582,   135,   126,    51,    88,    19,    59,   127,    10,
   nil,   543,   nil,    -6,   487,   501,   117,   237,    -2,   nil,
    21,   nil,   nil,   nil,   165,   529,    24,     6,   nil,   nil,
    49,   473,   nil,   nil,   121,    79,   nil,   nil ]

racc_action_default = [
    -1,   -62,    -2,    -3,    -6,   -20,    -8,    -9,   -10,   -11,
   -12,   -13,   -14,   -15,   -16,   -17,   -18,   -62,   -21,   -22,
   -23,   -24,   -25,   -26,   -53,   -49,   -62,   -62,   -62,   -62,
    -5,   -20,   -62,   -62,   -62,   -62,   -62,   -62,   -62,   -62,
   -62,   -62,   -62,   -62,   -62,    -7,   -62,   -27,   -62,   -31,
   -62,   -62,   -51,   -62,   -62,    98,    -4,   -52,   -37,   -38,
   -39,   -40,   -41,   -42,   -43,   -44,   -45,   -46,   -47,   -48,
   -19,   -32,   -29,   -62,   -54,   -50,   -62,   -62,   -62,   -59,
   -34,   -61,   -28,   -30,   -62,   -55,   -62,   -62,   -58,   -35,
   -62,   -33,   -56,   -57,   -62,   -62,   -36,   -60 ]

racc_goto_table = [
    30,    45,    90,    73,     2,     1,    79,    81,    47,   nil,
   nil,   nil,   nil,    46,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    56,   nil,   nil,    58,
    59,    60,    61,    62,    63,    64,    65,    66,    67,    68,
    69,    82,   nil,   nil,    71,   nil,    74,    75,    97,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    85,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    91,    86,    87,   nil,    30,    30 ]

racc_goto_check = [
     4,     3,    18,    17,     2,     1,    19,    19,    16,   nil,
   nil,   nil,   nil,     3,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,     3,   nil,   nil,     3,
     3,     3,     3,     3,     3,     3,     3,     3,     3,     3,
     3,    16,   nil,   nil,     3,   nil,     3,     3,    19,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,     3,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
     3,     2,     2,   nil,     4,     4 ]

racc_goto_pointer = [
   nil,     5,     4,    -4,    -2,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   -16,   -45,   -78,   -47 ]

racc_goto_default = [
   nil,   nil,   nil,     3,     4,     6,     7,     8,     9,    10,
    11,    12,    13,    14,    15,    16,   nil,   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  0, 37, :_reduce_1,
  1, 37, :_reduce_2,
  1, 38, :_reduce_3,
  3, 38, :_reduce_4,
  2, 38, :_reduce_5,
  1, 38, :_reduce_6,
  2, 38, :_reduce_7,
  1, 39, :_reduce_none,
  1, 39, :_reduce_none,
  1, 39, :_reduce_none,
  1, 39, :_reduce_none,
  1, 39, :_reduce_none,
  1, 39, :_reduce_none,
  1, 39, :_reduce_none,
  1, 39, :_reduce_none,
  1, 39, :_reduce_none,
  1, 39, :_reduce_none,
  1, 39, :_reduce_none,
  3, 39, :_reduce_19,
  1, 40, :_reduce_none,
  1, 40, :_reduce_none,
  1, 41, :_reduce_22,
  1, 41, :_reduce_23,
  1, 41, :_reduce_24,
  1, 41, :_reduce_25,
  1, 41, :_reduce_26,
  2, 42, :_reduce_27,
  4, 42, :_reduce_28,
  2, 52, :_reduce_29,
  3, 52, :_reduce_30,
  1, 52, :_reduce_31,
  1, 53, :_reduce_32,
  3, 53, :_reduce_33,
  0, 54, :_reduce_34,
  1, 54, :_reduce_35,
  3, 54, :_reduce_36,
  3, 43, :_reduce_37,
  3, 43, :_reduce_38,
  3, 43, :_reduce_39,
  3, 43, :_reduce_40,
  3, 43, :_reduce_41,
  3, 43, :_reduce_42,
  3, 43, :_reduce_43,
  3, 43, :_reduce_44,
  3, 43, :_reduce_45,
  3, 43, :_reduce_46,
  3, 43, :_reduce_47,
  3, 43, :_reduce_48,
  1, 44, :_reduce_49,
  3, 45, :_reduce_50,
  2, 48, :_reduce_51,
  3, 48, :_reduce_52,
  1, 46, :_reduce_53,
  3, 47, :_reduce_54,
  4, 49, :_reduce_55,
  3, 55, :_reduce_56,
  3, 55, :_reduce_57,
  2, 55, :_reduce_58,
  3, 50, :_reduce_59,
  6, 50, :_reduce_60,
  3, 51, :_reduce_61 ]

racc_reduce_n = 62

racc_shift_n = 98

racc_token_table = {
  false => 0,
  :error => 1,
  :DEF => 2,
  :CLASS => 3,
  :NEWLINE => 4,
  :NUMBER => 5,
  :STRING => 6,
  :TRUE => 7,
  :FALSE => 8,
  :NIL => 9,
  :IDENTIFIER => 10,
  :CONSTANT => 11,
  :END => 12,
  "." => 13,
  "!" => 14,
  "*" => 15,
  "/" => 16,
  "+" => 17,
  "-" => 18,
  ">" => 19,
  ">=" => 20,
  "<" => 21,
  "<=" => 22,
  "==" => 23,
  "!=" => 24,
  "&&" => 25,
  "||" => 26,
  "=" => 27,
  "," => 28,
  "(" => 29,
  ")" => 30,
  ";" => 31,
  "@" => 32,
  ":" => 33,
  "{" => 34,
  "}" => 35 }

racc_nt_base = 36

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "DEF",
  "CLASS",
  "NEWLINE",
  "NUMBER",
  "STRING",
  "TRUE",
  "FALSE",
  "NIL",
  "IDENTIFIER",
  "CONSTANT",
  "END",
  "\".\"",
  "\"!\"",
  "\"*\"",
  "\"/\"",
  "\"+\"",
  "\"-\"",
  "\">\"",
  "\">=\"",
  "\"<\"",
  "\"<=\"",
  "\"==\"",
  "\"!=\"",
  "\"&&\"",
  "\"||\"",
  "\"=\"",
  "\",\"",
  "\"(\"",
  "\")\"",
  "\";\"",
  "\"@\"",
  "\":\"",
  "\"{\"",
  "\"}\"",
  "$start",
  "Program",
  "Expressions",
  "Expression",
  "Terminator",
  "Literal",
  "Call",
  "Operator",
  "GetConstant",
  "SetConstant",
  "GetLocal",
  "SetLocal",
  "GetGlobal",
  "SetGlobal",
  "Def",
  "Class",
  "Arguments",
  "ArgList",
  "ParamList",
  "Block" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'grammar.y.rb', 28)
  def _reduce_1(val, _values, result)
     result = Nodes.new([])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 29)
  def _reduce_2(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 33)
  def _reduce_3(val, _values, result)
     result = Nodes.new(val)
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 34)
  def _reduce_4(val, _values, result)
     result = val[0] << val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 35)
  def _reduce_5(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 36)
  def _reduce_6(val, _values, result)
     result = Nodes.new([])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 37)
  def _reduce_7(val, _values, result)
     result = Nodes.new([val[1]])
    result
  end
.,.,

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

# reduce 15 omitted

# reduce 16 omitted

# reduce 17 omitted

# reduce 18 omitted

module_eval(<<'.,.,', 'grammar.y.rb', 52)
  def _reduce_19(val, _values, result)
     result = val[1]
    result
  end
.,.,

# reduce 20 omitted

# reduce 21 omitted

module_eval(<<'.,.,', 'grammar.y.rb', 61)
  def _reduce_22(val, _values, result)
     result = NumberNode.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 62)
  def _reduce_23(val, _values, result)
     result = StringNode.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 63)
  def _reduce_24(val, _values, result)
     result = TrueNode.new
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 64)
  def _reduce_25(val, _values, result)
     result = FalseNode.new
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 65)
  def _reduce_26(val, _values, result)
     result = NilNode.new
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 69)
  def _reduce_27(val, _values, result)
     result = CallNode.new(nil, val[0], val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 71)
  def _reduce_28(val, _values, result)
     result = CallNode.new(val[0], val[2], val[3])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 75)
  def _reduce_29(val, _values, result)
     result = []
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 76)
  def _reduce_30(val, _values, result)
     result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 77)
  def _reduce_31(val, _values, result)
     result = []
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 81)
  def _reduce_32(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 82)
  def _reduce_33(val, _values, result)
     result = val[0] << val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 86)
  def _reduce_34(val, _values, result)
     result = []
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 87)
  def _reduce_35(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 88)
  def _reduce_36(val, _values, result)
     result = val[0] << val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 92)
  def _reduce_37(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 93)
  def _reduce_38(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 94)
  def _reduce_39(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 95)
  def _reduce_40(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 96)
  def _reduce_41(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 97)
  def _reduce_42(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 98)
  def _reduce_43(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 99)
  def _reduce_44(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 100)
  def _reduce_45(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 101)
  def _reduce_46(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 102)
  def _reduce_47(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 103)
  def _reduce_48(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 107)
  def _reduce_49(val, _values, result)
     result = GetConstantNode.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 111)
  def _reduce_50(val, _values, result)
     result = SetConstantNode.new(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 115)
  def _reduce_51(val, _values, result)
     result = GetGlobalNode.new(nil, val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 116)
  def _reduce_52(val, _values, result)
     result = GetGlobalNode.new(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 120)
  def _reduce_53(val, _values, result)
     result = GetLocalNode.new(nil, val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 124)
  def _reduce_54(val, _values, result)
     result = SetLocalNode.new(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 128)
  def _reduce_55(val, _values, result)
     result = SetGlobalNode.new(val[1], val[3])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 132)
  def _reduce_56(val, _values, result)
     result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 133)
  def _reduce_57(val, _values, result)
     result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 134)
  def _reduce_58(val, _values, result)
     result = Nodes.new([])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 138)
  def _reduce_59(val, _values, result)
     result = DefNode.new(val[1], [], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 140)
  def _reduce_60(val, _values, result)
     result = DefNode.new(val[1], val[3], val[5])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 144)
  def _reduce_61(val, _values, result)
     result = ClassNode.new(val[1], val[2])
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class Parser
